[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LaserExperiments = "eb1875a3-6e0d-577e-a250-3e610cb08925"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[sources]
LaserExperiments = {path = "/Users/uwe/Work/jlProjects/QEDjl-project/LaserExperiments.jl/docs/.."}

[compat]
Documenter = "1"
